// <auto-generated />
namespace sklep_internetowy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Zmiana_nazwy_kolumny : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Zmiana_nazwy_kolumny));
        
        string IMigrationMetadata.Id
        {
            get { return "202406021658063_Zmiana_nazwy_kolumny"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
